# 安全工具导航系统配置文件
# 从 ../js/config.js 导出
# 导出时间: 2025-07-10 22:45:24
# 注意: 修改此文件后请使用 'config-editor import' 命令导入到JS文件

app:
    description: 专注于安全技术的知识库导航系统，包含漏洞挖掘、Web安全、逆向分析等多个领域的资源。
    title: 安全知识库导航
    version: 2.0.0
content:
    learning_resources:
        categories:
            - icon: fas fa-book-open
              id: tutorials
              name: 教程文档
              subcategories:
                - contentType: table
                  data:
                    - description: Web应用安全风险学习指南
                      links:
                        - text: 官网
                          url: https://owasp.org/www-project-top-ten/
                        - text: 中文版
                          url: https://owasp.org/Top10/zh_CN/
                      name: OWASP Top 10
                      tags:
                        - OWASP
                        - Web安全
                        - 基础教程
                    - description: 系统性的Web安全学习资料
                      links:
                        - text: GitHub
                          url: https://github.com/websec/websec
                      name: Web安全学习笔记
                      tags:
                        - 学习笔记
                        - 系统性
                  description: Web应用安全相关的学习教程
                  id: web_security_tutorials
                  name: Web安全教程
                - contentType: table
                  data:
                    - description: 漏洞练习平台
                      links:
                        - text: GitHub
                          url: https://github.com/digininja/DVWA
                        - text: 在线版
                          url: http://www.dvwa.co.uk/
                      name: DVWA
                      tags:
                        - 靶场
                        - 练习平台
                    - description: OWASP官方Web安全教学平台
                      links:
                        - text: GitHub
                          url: https://github.com/WebGoat/WebGoat
                      name: WebGoat
                      tags:
                        - OWASP
                        - 教学平台
                  description: 安全技能实战练习平台
                  id: practice_platforms
                  name: 实战平台
    security_frameworks:
        categories:
            - icon: fas fa-code
              id: web_frameworks
              name: Web安全框架
              subcategories:
                - contentType: table
                  data:
                    - description: Laravel框架的安全最佳实践
                      links:
                        - text: 官网
                          url: https://laravel.com/docs/security
                      name: Laravel Security
                  id: php_frameworks
                  name: PHP安全框架
    security_news:
        categories:
            - icon: fas fa-newspaper
              id: news_sources
              name: 资讯来源
              subcategories:
                - contentType: table
                  data:
                    - description: 国内领先的网络安全行业门户
                      links:
                        - text: 官网
                          url: https://www.freebuf.com/
                      name: FreeBuf
                  id: security_blogs
                  name: 安全博客
    security_tools:
        categories:
            - icon: fas fa-search
              id: recon
              name: 信息收集
              subcategories:
                - contentType: table
                  data:
                    - description: 集成了30个工具的信息收集利器
                      links:
                        - text: GitHub
                          url: https://github.com/six2dez/reconftw
                      name: reconftw
                      tags:
                        - 信息收集
                        - 自动化
                        - 集成工具
                    - description: 资产扫描监控扫描系统
                      links:
                        - text: GitHub
                          url: https://github.com/awake1t/linglong
                      name: linglong
                      tags:
                        - 资产监控
                        - 扫描系统
                    - description: 快速侦察与目标关联的互联网资产，构建基础资产信息库
                      links:
                        - text: GitHub
                          url: https://github.com/TophantTechnology/ARL
                      name: ARL(灯塔)
                      tags:
                        - 资产侦察
                        - 信息库
                  id: asset_discovery
                  name: 资产发现
                - contentType: table
                  data:
                    - description: 集合了多个网络搜索平台，可以快速在多个网络搜索平台搜索信息并且合并筛选及导出
                      links:
                        - text: GitHub
                          url: https://github.com/ExpLangcn/InfoSearchAll
                      name: InfoSearchAll
                      tags:
                        - 多平台搜索
                        - 信息收集
                    - description: 使用EloomEye的第三方api-GUI界面
                      links:
                        - text: GitHub
                          url: https://github.com/zcgyjx/ThunderSearch
                      name: ThunderSearch
                      tags:
                        - GUI工具
                        - API接口
                  id: subdomain
                  name: 子域名收集
            - icon: fas fa-bug
              id: vulnerability
              name: 漏洞检测
              subcategories:
                - contentType: table
                  data:
                    - description: 从第三方平台获取目标网页内容
                      links:
                        - text: GitHub
                          url: https://github.com/tomnomnom/waybackurls
                      name: waybackurls
                      tags:
                        - Web安全
                        - 历史数据
                    - description: 从多个网站搜取目标相关信息
                      links:
                        - text: GitHub
                          url: https://github.com/lc/gau
                      name: gau
                      tags:
                        - 信息收集
                        - 多源搜索
                  description: Web应用安全测试工具
                  id: web_security
                  name: Web安全
    vulnerability_research:
        categories:
            - icon: fas fa-database
              id: vuln_databases
              name: 漏洞库
              subcategories:
                - contentType: table
                  data:
                    - description: 通用漏洞披露平台
                      links:
                        - text: 官网
                          url: https://cve.mitre.org/
                      name: CVE官方数据库
                  id: cve
                  name: CVE
    vulnerability_research1:
        categories:
            - icon: fas fa-globe
              id: web_vulns
              name: Web漏洞
              subcategories:
                - id: injection_vulns
                  name: 注入类漏洞
                  subcategories:
                    - id: sql_injection
                      name: SQL注入
                      subcategories:
                        - contentType: table
                          data:
                            - description: 自动化SQL注入和数据库接管工具
                              links:
                                - text: GitHub
                                  url: https://github.com/sqlmapproject/sqlmap
                              name: sqlmap
                          id: sql_injection_basic
                          name: 基础SQL注入
                        - contentType: table
                          data:
                            - description: NoSQL数据库自动化注入工具
                              links:
                                - text: GitHub
                                  url: https://github.com/codingo/NoSQLMap
                              name: NoSQLMap
                          id: sql_injection_advanced
                          name: 高级SQL注入
                    - contentType: table
                      data:
                        - description: 自动化命令注入利用工具
                          links:
                            - text: GitHub
                              url: https://github.com/commixproject/commix
                          name: commix
                      id: command_injection
                      name: 命令注入
                - id: xss_vulns
                  name: XSS跨站脚本
                  subcategories:
                    - contentType: table
                      data:
                        - description: 高级XSS检测套件
                          links:
                            - text: GitHub
                              url: https://github.com/s0md3v/XSStrike
                          name: XSStrike
                      id: reflected_xss
                      name: 反射型XSS
                    - contentType: table
                      data:
                        - description: XSS防御库
                          links:
                            - text: GitHub
                              url: https://github.com/cure53/DOMPurify
                          name: DOMPurify
                      id: stored_xss
                      name: 存储型XSS
            - icon: fas fa-mobile-alt
              id: mobile_vulns
              name: 移动应用漏洞
              subcategories:
                - id: android_vulns
                  name: Android漏洞
                  subcategories:
                    - contentType: table
                      data:
                        - description: 移动安全框架
                          links:
                            - text: GitHub
                              url: https://github.com/MobSF/Mobile-Security-Framework-MobSF
                          name: MobSF
                      id: android_webview
                      name: WebView漏洞
                - contentType: table
                  data:
                    - description: iOS应用安全评估工具
                      links:
                        - text: GitHub
                          url: https://github.com/dmayer/idb
                      name: idb
                  id: ios_vulns
                  name: iOS漏洞
home:
    features:
        - description: 支持多层级的知识分类，方便查找和管理
          icon: mdi mdi-folder-multiple
          title: 多层级导航
        - description: 快速搜索功能，帮助您迅速定位所需内容
          icon: mdi mdi-magnify
          title: 实时搜索
        - description: 可自定义的导航结构和内容展示
          icon: mdi mdi-cog
          title: 个性化配置
    quickLinks:
        - items:
            - link: '#web/analysis'
              title: Web漏洞分析技巧
            - link: '#attack/summary'
              title: 常见攻击方式总结
            - link: '#tools/guide'
              title: 安全工具使用指南
          title: 最近更新
        - items:
            - link: '#vuln/sqli/advanced'
              title: SQL注入进阶
            - link: '#reverse/basic'
              title: 逆向分析基础
            - link: '#dev/security'
              title: 安全开发实践
          title: 热门推荐
    welcome: 欢迎使用安全知识库导航系统
tabs:
    - description: 收集和整理各类安全工具
      icon: fas fa-shield-alt
      id: security_tools
      name: 安全工具
    - description: 安全学习相关的教程和资料
      icon: fas fa-book
      id: learning_resources
      name: 学习资源
    - description: 各种安全开发和测试框架
      icon: fas fa-cubes
      id: security_frameworks
      name: 安全框架
    - description: 安全行业动态和资讯
      icon: fas fa-newspaper
      id: security_news
      name: 安全资讯
    - description: 漏洞挖掘和分析相关内容
      icon: fas fa-bug
      id: vulnerability_research
      name: 漏洞研究
    - description: 漏洞挖掘和分析相关内容
      icon: fas fa-bug
      id: vulnerability_research1
      name: 漏洞研究111222
